### ISSUE TITLE
remove fonts-indic meta package and autoremove

### ISSUE THREAD

**Issue by KushagraKarira** [ksguin/Falguni#2]
Hi, checking from debian, it uses the [fonts-indic](https://packages.debian.org/bullseye/fonts-indic) metapackage, and all other indian fonts depend on it.
So removing that package with `sudo apt purge fonts-indic --autoremove` will probably clean all

**Comment by ksguin** [comment]
The [fonts-indic](https://packages.debian.org/bullseye/fonts-indic) metapackage has the following dependent meta-packages :
* fonts-beng
* fonts-deva
* fonts-gujr
* fonts-guru
* fonts-knda
* fonts-mlym
* fonts-orya
* **fonts-pagul**
* fonts-taml
* fonts-telu

The **replacement** [fonts-noto](https://www.google.com/get/noto/) by Google which contains many Indic fonts under the moniker of Noto Sans & Noto Serif covers almost all in the list (to avoid Tofu) above **except** "[**fonts-pagul**](https://packages.debian.org/sid/fonts-pagul)".

`sudo apt purge fonts-indic --autoremove` will definitely remove all, but if someone requires **fonts-pagul** and probably does not want to uninstall it, then that might cause a problem!

**Comment by KushagraKarira** [comment]
okay, makes sense
even i require fonts-deva and fonts-gujr daily - also it's not that much space anyways
